services:
  - type: web
    name: echo-backend
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: PORT
        value: "3000"

